source/api/urls.py
from django.urls import path, include
from rest_framework import routers
from .views import LikeViewSet, CommentViewSet

router = routers.DefaultRouter()
router.register(r'likes', LikeViewSet)
router.register(r'comments', CommentViewSet)


app_name = 'api'

urlpatterns = [
    path('', include(router.urls)),
]

source/gallery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('api/', include('api.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path
from .views import IndexView, PhotoView, PhotoCreateView, PhotoUpdateView, PhotoDeleteView
from django.contrib.auth.views import LoginView, LogoutView


app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('photo/<int:pk>/', PhotoView.as_view(), name='photo_detail'),
    path('photo/create/', PhotoCreateView.as_view(), name='photo_create'),
    path('photo/<int:pk>/update/', PhotoUpdateView.as_view(), name='photo_update'),
    path('photo/<int:pk>/delete/', PhotoDeleteView.as_view(), name='photo_delete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

source/api/models.py
from django.db import models

# Create your models here.

source/webapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Photo(models.Model):
    photo = models.ImageField(upload_to='photos', verbose_name='Фото')
    signature = models.CharField(max_length=200, verbose_name='Подпись')
    create_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    author = models.ForeignKey(User, related_name='photos', on_delete=models.CASCADE, verbose_name='Автор')
    like = models.ManyToManyField(User, through='webapp.Like', blank=True, verbose_name='userslike')

    def __str__(self):
        return self.signature


class Comment(models.Model):
    descr = models.TextField(max_length=1000, verbose_name='Текст')
    photo = models.ForeignKey('webapp.Photo', related_name='photo_comments', on_delete=models.CASCADE, verbose_name='Фотография')
    author = models.ForeignKey(User, related_name='author_comments', on_delete=models.CASCADE, verbose_name='Автор')
    create_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')

    def __str__(self):
        return self.descr


class Like(models.Model):
    photo = models.ForeignKey(Photo, on_delete=models.CASCADE, null=True, blank=True, verbose_name='photo', related_name='photolikes')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True, verbose_name='author', related_name='userlikes')

source/api/views.py
from webapp.models import Photo, Like, Comment

from rest_framework import viewsets
from rest_framework.permissions import DjangoModelPermissions, IsAuthenticatedOrReadOnly, IsAuthenticated, AllowAny
from rest_framework.response import Response

SAFE_METHODS = ('GET', 'HEAD', 'OPTIONS')

from .serializers import LikeSerializer, CommentSerializer

class LikeViewSet(viewsets.ModelViewSet):
    permission_classes = [DjangoModelPermissions]
    serializer_class = LikeSerializer
    queryset = Like.objects.all()

    def create(self, request, *args, **kwargs):
        pk = request.data.get('photo')
        photo = Photo.objects.get(pk=pk)

        if self.queryset.filter(photo=photo):
            return Response({'error': 'You have already liked it'}, status=400)
        photo.likenum += 1
        photo.save()
        return super(LikeViewSet, self).create(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        pk = request.data.get('photo')
        photo = Photo.objects.get(pk=pk)
        if not self.queryset.filter(photo=photo):
            return Response({'error': 'No likes yet'}, status=400)
        photo.likenum -= 1
        photo.save()
        return super(LikeViewSet, self).create(request, *args, **kwargs)


class CommentViewSet(viewsets.ModelViewSet):
    permission_classes = [DjangoModelPermissions]
    serializer_class = CommentSerializer
    queryset = Comment.objects.all()


    def get_permissions(self):
        if self.request.method in SAFE_METHODS:
          return [AllowAny()]

        elif self.request.method == 'POST':
            return [IsAuthenticated()]
        else:
            return [DjangoModelPermissions()]

source/webapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import reverse, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages


from webapp.models import Photo, Comment

class IndexView(ListView):
    model = Photo
    template_name = 'index.html'
    context_object_name = 'photos'
    ordering = ['-create_at']


class PhotoView(DetailView):
    template_name = 'photo.html'
    model = Photo
    context_object_name = 'photo'
    ordering = ['-create_at']
    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['comments']= self.object.photo_comments.all().order_by('-create_at')
        return context


class PhotoCreateView( CreateView, LoginRequiredMixin):
    model = Photo
    template_name = 'create.html'
    fields = ('signature', 'photo')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('webapp:photo_detail', kwargs={'pk': self.object.pk})


class PhotoUpdateView(UpdateView, UserPassesTestMixin):
    model = Photo
    template_name = 'update.html'
    fields = ('signature', 'photo')
    # context_object_name = 'photos'

    def test_func(self):
        photo_pk = self.kwargs.get('pk')
        photo = Photo.objects.get(pk=photo_pk)
        return self.request.user == photo.author or self.request.user.has_perm('webapp.change_photo')

    def get_success_url(self):
        return reverse('webapp:photo_detail', kwargs={'pk': self.object.pk})


class PhotoDeleteView(DeleteView, UserPassesTestMixin):
    model = Photo
    template_name = 'delete.html'
    context_object_name = 'photo'
    success_url = reverse_lazy('webapp:index')

    def test_func(self):
        photo_pk = self.kwargs.get('pk')
        photo = Photo.objects.get(pk=photo_pk)
        return self.request.user == photo.author or self.request.user.has_perm('webapp.change_photo')

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block styles %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item"><a href="{% url 'webapp:index' %}" class="nav-link">На главную</a></li>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
                <li class="nav-item"><a href="{% url 'webapp:logout' %}" class="nav-link">Выход</a></li>
                <li class="nav-item"><a href="{% url 'webapp:photo_create' %}" class="nav-link">Добавить фотографию</a></li>
            {% else %}
                <li class="nav-item"><a href="{% url 'webapp:login' %}" class="nav-link">Вход</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
<div class="container mt-3 mb-3">
{#    {% include 'partial/messages.html' %}#}
    {% block content %}{% endblock %}

    <div class="modal fade" id="statsModal" tabindex="-1" role="dialog" aria-labelledby="statsModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="statsModalLabel">Статистика</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

source/webapp/templates/create.html
{% extends 'base.html' %}
{% block title %}Добавить фотографию{% endblock %}
{% block content %}
    <h1 class="text-center">Добавить фотографию</h1>
    <form action="{% url "webapp:photo_create" %}" method="POST" enctype="multipart/form-data">
        {% include 'partial/form.html' %}
        <input type="submit" value="Создать" class="btn btn-primary">
    </form>
{% endblock %}

source/webapp/templates/delete.html
{% extends 'base.html' %}
{% block title %}Удалить фотографию{% endblock %}
{% block content %}
    <h3 class="text-center">Фото {{ photo }} будет удален</h3>
    <form class="text-center" action="{% url "webapp:photo_delete" photo.pk %}"
          method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="submit" value="ОК" class="btn btn-danger">
        <a href="{% url 'webapp:index' %}" class="btn btn-secondary">Отмена</a>
    </form>
{% endblock %}

{#{% extends 'base.html' %}#}
{##}
{#{% block title %}Удалить фотографию{% endblock %}#}
{##}
{#{% block menu %}#}
{#    <li><a href="{% url 'webapp:article_view' photo.pk %}">View</a></li>#}
{#{% endblock %}#}
{##}
{#{% block content %}#}
{#    <h1>Вы уверены что хотите удалить фотографию "{{ photo }}"?</h1>#}
{#    <form method="POST" action="{% url 'webapp:photo_delete' photo.pk %}" class="text-center">#}
{#        {% csrf_token %}#}
{#        <p><input type="submit" value="Подтвердить"></p>#}
{#        <p><a href="{% url 'webapp:photo_view' photo.pk %}">Отмена</a></p>#}
{#    </form>#}
{#{% endblock %}#}

source/webapp/templates/index.html
{% extends 'base.html' %}
{% block title %}Галерея{% endblock %}
{% block content %}
    <h1 class="text-center">Галерея</h1>
    <div class="row">
        {% for photo in photos %}
            <div class="col col-3">
                <div class="card">
                    {% if photo.photo %}
                        <img src="{{ photo.photo.url }}" class="card-img-top" alt="{{ photo.signature }}">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title">{{ photo.signature }}</h5>
                        <p class="card-text">автор: {{ photo.author }}  дата создания {{ photo.create_at }}</p>
                        <a href="{% url "webapp:photo_detail" photo.pk %}"
                           class="btn btn-primary">Посмотреть</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

source/webapp/templates/partial/form.html
{% load widget_tweaks %}
{% csrf_token %}
{% for error in form.non_field_errors %}
    <p class="text-danger">{{ error }}</p>
{% endfor %}
{% for field in form %}
    <div class="form-group">
        {% include 'partial/form_field.html' %}
    </div>
{% endfor %}

source/webapp/templates/partial/form_field.html
{% load widget_tweaks %}
<label for="{{ field.id_for_label }}" class="mr-3">{{ field.label }}</label>
{% if field|field_type == 'imagefield' or field|field_type == 'filefield' or field|field_type == 'booleanfield' %}
    {{ field }}
{% else %}
    {{ field|add_class:"form-control" }}
{% endif %}
{% for error in field.errors %}
    <p class="text-danger">{{ error }}</p>
{% endfor %}

source/webapp/templates/photo.html
{% extends 'base.html' %}
{% block title %}{{ photo.signature }}{% endblock %}
{% block content %}
    <div class="text-center">
        <h1>{{ photo.signature }}</h1>
        <div class="row">
            <div class="col col-12 col-sm-10 col-md-8 col-lg-6 m-auto">
                <img src="{{ photo.photo.url }}" class="img-fluid" alt="{{ photo.signature }}">
            </div>
        </div>
        {% if request.user.is_authenticated %}
            <p><a href="{% url 'webapp:photo_update' photo.pk %}" class="btn btn-primary">Изменить</a></p>
            <p><a href="{% url 'webapp:photo_delete' photo.pk %}" class="btn btn-primary">Удалить</a></p>
        {% else %}
            <p><a href="{% url 'webapp:login' %}" class="btn btn-primary">Войти</a></p>
        {% endif %}
     <div class="text-center">
        {% for comment in comments %}
            <div class="#">
                <p>{{ comment.author }} commented at {{ comment.create_at|date:'d.m.Y H:i:s' }}</p>
                <p>{{ comment.descr }}</p>
            </div>
        {% empty %}
            <p>No comments yet.</p>
        {% endfor %}
     </div>
    </div>
{% endblock %}

{#./manage.py dumpdata --indent=2 webapp auth.user > webapp/fixtures/dump.json#}

source/webapp/templates/update.html
{% extends 'base.html' %}
{% block title %}Обновить фото{% endblock %}
{% block content %}
    <h1 class="text-center">Обновить фото</h1>
    <form action="{% url "webapp:photo_update" photo.pk %}" method="POST" enctype="multipart/form-data">
        {% include 'partial/form.html' %}
        <input type="submit" value="Обновить" class="btn btn-primary">
    </form>
{% endblock %}